# Generated by Django 3.2.6 on 2021-09-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210909_1959'),
        ('sales', '0002_salesplan_salesrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesplan',
            name='planned_qty_kg',
        ),
        migrations.CreateModel(
            name='SalesPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.salesplanitem'),
        ),
    ]
