# Generated by Django 3.2.6 on 2021-09-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20210911_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlan1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.salesplanitem')),
            ],
        ),
    ]
