# Generated by Django 3.2.6 on 2021-09-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('sales_channel_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('sales_channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('belongs_to_sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.saleschannel')),
                ('customer_portfolio', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
