# Generated by Django 3.2.6 on 2021-09-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210909_1959'),
        ('sales', '0003_auto_20210909_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplan',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product'),
        ),
    ]
