# Generated by Django 3.2.6 on 2021-09-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesplan1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_portfolio',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='saleschannel',
            old_name='sales_channel_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='saleschannel',
            old_name='sales_channel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salesrecords',
            old_name='sales_qty_kg',
            new_name='quantity',
        ),
        migrations.DeleteModel(
            name='SalesPlan1',
        ),
    ]
