# Generated by Django 3.2.6 on 2021-09-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_subgroup', models.CharField(max_length=100, unique=True)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.productgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=10)),
                ('product_weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('product_weight_text', models.CharField(max_length=10)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.productgroup')),
                ('product_subgroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.productsubgroup')),
            ],
        ),
    ]
