# Generated by Django 3.2.6 on 2021-09-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210912_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='group',
            new_name='product_group',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subgroup',
            new_name='product_subgroup',
        ),
        migrations.RenameField(
            model_name='productgroup',
            old_name='group',
            new_name='product_group',
        ),
        migrations.RenameField(
            model_name='productsubgroup',
            old_name='group',
            new_name='product_group',
        ),
        migrations.RenameField(
            model_name='productsubgroup',
            old_name='subgroup',
            new_name='product_subgroup',
        ),
    ]
